In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, roc_auc_score

import joblib

In [2]:
df = pd.read_csv("Heart_Failure_Dataset.csv")
df.head()

,Age,Gender,Ethnicity,BMI,Systolic_BP,Diastolic_BP,Resting_Heart_Rate,Respiratory_Rate,Smoking_Status,Alcohol_Consumption,...,Proteinuria,HbA1c,Fasting_Glucose,Diabetes_Status,Potassium,Sodium,Phosphate,Calcium,Heart_Failure_Severity,Readmitted
0,68,Male,Other,39.4,137,105,78,20,No,NaN,...,0,4.6,268.7,1,5.2,140.3,3.1,8.0,2,1
1,81,Female,White,27.7,123,67,55,28,Yes,Moderate,...,0,11.1,299.5,1,6.0,131.0,3.4,9.8,1,1
2,58,Female,Asian,43.3,105,97,86,28,Yes,Moderate,...,1,9.5,158.5,1,5.5,146.3,4.0,7.8,2,0
3,44,Female,Hispanic,32.4,167,63,82,16,Yes,Heavy,...,1,4.7,160.0,1,3.8,149.6,4.9,7.9,2,1
4,72,Female,Hispanic,34.1,105,96,95,19,Yes,Moderate,...,0,5.7,239.3,1,4.7,153.4,2.6,9.5,2,1

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 25 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Age                     5000 non-null   int64
 1   Gender                  5000 non-null   object
 2   Ethnicity               5000 non-null   object
 3   BMI                     5000 non-null   float64
 4   Systolic_BP             5000 non-null   int64
 5   Diastolic_BP            5000 non-null   int64
 6   Resting_Heart_Rate      5000 non-null   int64
 7   Respiratory_Rate        5000 non-null   int64
 8   Smoking_Status          5000 non-null   object
 9   Alcohol_Consumption     3383 non-null   object
 10  Serum_Creatinine        5000 non-null   float64
 11  eGFR                    5000 non-null   float64
 12  BUN                     5000 non-null   float64
 13  Albumin                 5000 non-null   float64
 14  UACR                    5000 non-null   float64
 15  Proteinuria             5000 non-null   int64
 16  HbA1c                   5000 non-null   float64
 17  Fasting_Glucose         5000 non-null   float64
 18  Diabetes_Status         5000 non-null   int64
 19  Potassium               5000 non-null   float64
 20  Sodium                  5000 non-null   float64
 21  Phosphate               5000 non-null   float64
 22  Calcium                 5000 non-null   float64
 23  Heart_Failure_Severity  5000 non-null   int64
 24  Readmitted              5000 non-null   int64
dtypes: float64(12), int64(9), object(4)
memory usage: 976.7+ KB

In [4]:
df.describe()

,Age,BMI,Systolic_BP,Diastolic_BP,Resting_Heart_Rate,Respiratory_Rate,Serum_Creatinine,eGFR,BUN,Albumin,...,Proteinuria,HbA1c,Fasting_Glucose,Diabetes_Status,Potassium,Sodium,Phosphate,Calcium,Heart_Failure_Severity,Readmitted
count,5000.00000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,...,5000.000000,5000.000000,5000.000000,5000.000000,5000.00000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000
mean,59.70120,31.446640,139.555400,84.393400,84.488000,20.537200,2.744308,62.099000,33.415420,3.760440,...,0.508800,8.251880,185.599900,0.495200,4.75102,142.658540,3.971680,9.227760,1.605400,0.494600
std,17.26688,7.751791,23.177031,14.386119,20.071025,5.138317,1.304855,33.205364,15.305786,1.009952,...,0.499973,2.156998,65.731022,0.500027,1.00346,7.286902,1.165999,1.009921,0.588014,0.500021
min,30.00000,18.000000,100.000000,60.000000,50.000000,12.000000,0.500000,5.000000,7.000000,2.000000,...,0.000000,4.500000,70.000000,0.000000,3.00000,130.000000,2.000000,7.500000,0.000000,0.000000
25%,45.00000,24.900000,119.000000,72.000000,67.000000,16.000000,1.630000,33.000000,20.075000,2.900000,...,0.000000,6.400000,129.175000,0.000000,3.90000,136.275000,2.900000,8.300000,1.000000,0.000000
50%,60.00000,31.400000,140.000000,85.000000,85.000000,20.000000,2.730000,61.700000,33.400000,3.800000,...,1.000000,8.300000,184.950000,0.000000,4.80000,142.700000,4.000000,9.200000,2.000000,0.000000
75%,75.00000,38.100000,159.000000,97.000000,102.000000,25.000000,3.890000,91.100000,46.600000,4.600000,...,1.000000,10.200000,242.700000,1.000000,5.60000,149.100000,5.000000,10.100000,2.000000,1.000000
max,89.00000,45.000000,179.000000,109.000000,119.000000,29.000000,5.000000,120.000000,60.000000,5.500000,...,1.000000,12.000000,300.000000,1.000000,6.50000,155.000000,6.000000,11.000000,2.000000,1.000000

In [5]:
df.isnull().sum()

Age                          0
Gender                       0
Ethnicity                    0
BMI                          0
Systolic_BP                  0
Diastolic_BP                 0
Resting_Heart_Rate           0
Respiratory_Rate             0
Smoking_Status               0
Alcohol_Consumption       1617
Serum_Creatinine             0
eGFR                         0
BUN                          0
Albumin                      0
UACR                         0
Proteinuria                  0
HbA1c                        0
Fasting_Glucose              0
Diabetes_Status              0
Potassium                    0
Sodium                       0
Phosphate                    0
Calcium                      0
Heart_Failure_Severity       0
Readmitted                   0
dtype: int64

In [6]:
X = df.drop(["Readmitted", "Heart_Failure_Severity"], axis=1)
y = df["Readmitted"]

In [7]:
print(df.columns)

Index(['Age', 'Gender', 'Ethnicity', 'BMI', 'Systolic_BP', 'Diastolic_BP',
       'Resting_Heart_Rate', 'Respiratory_Rate', 'Smoking_Status',
       'Alcohol_Consumption', 'Serum_Creatinine', 'eGFR', 'BUN', 'Albumin',
       'UACR', 'Proteinuria', 'HbA1c', 'Fasting_Glucose', 'Diabetes_Status',
       'Potassium', 'Sodium', 'Phosphate', 'Calcium', 'Heart_Failure_Severity',
       'Readmitted'],
      dtype='object')

In [8]:
categorical_features = [
    'Gender',
    'Ethnicity',
    'Smoking_Status',
    'Alcohol_Consumption',
    'Proteinuria',
    'Diabetes_Status'
]

numeric_features = [
    col for col in X.columns if col not in categorical_features
]

In [9]:
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer

preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), numeric_features),
        ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_features)
    ]
)

In [10]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [11]:
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression

logistic_model = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', LogisticRegression(max_iter=1000))
])

logistic_model.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  ['Age', 'BMI', 'Systolic_BP',
                                                   'Diastolic_BP',
                                                   'Resting_Heart_Rate',
                                                   'Respiratory_Rate',
                                                   'Serum_Creatinine', 'eGFR',
                                                   'BUN', 'Albumin', 'UACR',
                                                   'HbA1c', 'Fasting_Glucose',
                                                   'Potassium', 'Sodium',
                                                   'Phosphate', 'Calcium']),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['Gender', 'Ethnicity',
                                                   'Smoking_Status',
                                                   'Alcohol_Consumption',
                                                   'Proteinuria',
                                                   'Diabetes_Status'])])),
                ('classifier', LogisticRegression(max_iter=1000))])

In [12]:
from sklearn.ensemble import RandomForestClassifier

rf_model = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', RandomForestClassifier(
        n_estimators=200,
        random_state=42
    ))
])

rf_model.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  ['Age', 'BMI', 'Systolic_BP',
                                                   'Diastolic_BP',
                                                   'Resting_Heart_Rate',
                                                   'Respiratory_Rate',
                                                   'Serum_Creatinine', 'eGFR',
                                                   'BUN', 'Albumin', 'UACR',
                                                   'HbA1c', 'Fasting_Glucose',
                                                   'Potassium', 'Sodium',
                                                   'Phosphate', 'Calcium']),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['Gender', 'Ethnicity',
                                                   'Smoking_Status',
                                                   'Alcohol_Consumption',
                                                   'Proteinuria',
                                                   'Diabetes_Status'])])),
                ('classifier',
                 RandomForestClassifier(n_estimators=200, random_state=42))])

In [13]:
from sklearn.metrics import accuracy_score, roc_auc_score

models = {
    "Logistic Regression": logistic_model,
    "Random Forest": rf_model
}

for name, model in models.items():
    y_pred = model.predict(X_test)
    y_prob = model.predict_proba(X_test)[:, 1]
    
    print(name)
    print("Accuracy:", accuracy_score(y_test, y_pred))
    print("ROC-AUC:", roc_auc_score(y_test, y_prob))
    print("-" * 40)

Logistic Regression
Accuracy: 0.576
ROC-AUC: 0.6205100510051005
----------------------------------------
Random Forest
Accuracy: 0.589
ROC-AUC: 0.6325132513251326
----------------------------------------

In [14]:
best_model = rf_model

In [15]:
import joblib

joblib.dump(
    best_model.named_steps['preprocessor'],
    "preprocessor_hf.pkl"
)

joblib.dump(
    best_model.named_steps['classifier'],
    "best_classification_model_hf.pkl"
)

['best_classification_model_hf.pkl']

In [16]:
loaded_preprocessor = joblib.load("preprocessor_hf.pkl")
loaded_model = joblib.load("best_classification_model_hf.pkl")

sample = X.iloc[[0]]
sample_processed = loaded_preprocessor.transform(sample)

print("Prediction:", loaded_model.predict(sample_processed))
print("Probability:", loaded_model.predict_proba(sample_processed))

Prediction: [1]
Probability: [[0.165 0.835]]